# Generated by Django 3.2.4 on 2021-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created'], 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ['-created'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], default='green', max_length=10, unique=True, verbose_name='Цвет'),
        ),
    ]
