# Generated by Django 3.2.4 on 2021-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210606_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple')], default='green', max_length=10, verbose_name='Цвет'),
        ),
    ]
